// <auto-generated />
namespace Chemiklani.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SchoolTeam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SchoolTeam));
        
        string IMigrationMetadata.Id
        {
            get { return "201812161041396_SchoolTeam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
